---
- hosts: all
  sudo: yes
  vars:

    nodejs_version: "0.10"
    nodejs_packages:
      - pm2

    ghost_version: "0.7.0"
    ghost_user: apps
    ghost_location: /var/apps/ghost-{{ ghost_version }}
    ghost_config: ./ghost/config.prod.js
    ghost_theme: https://github.com/mmarcon/ghost-jhere-beta/archive/master.zip

    # list of apps to be managed by pm2
    pm2_apps:
      - "/var/apps/ghost-{{ ghost_version }}/index.js"

  roles:
    - nodejs
    - ghost

  pre_tasks:
    - name: create apps group
      group: name=apps state=present
    - name: create apps user
      user: name=apps comment="Apps User" group=apps home=/var/apps
    - name: create node apps directory
      file: path=/var/apps state=directory owner=apps group=apps mode=0775

  tasks:
    #nginx
    - name: install nginx
      apt: name=nginx state=present update_cache=yes
      notify:
        - start nginx
    - name: configure nginx
      copy: src={{ item }} dest=/etc/nginx/sites-available/
      with_fileglob:
        - ./nginx/*
      notify:
        - restart nginx

    #ghost theme
    - name: fetch theme
      get_url: url=https://github.com/mmarcon/ghost-jhere-beta/archive/master.zip dest=/tmp/jhere-beta.zip
      become: yes
      become_user: "{{ ghost_user }}"
    - name: extract theme
      unarchive: src=/tmp/jhere-beta.zip dest={{ ghost_location }}/content/themes copy=no
      become: yes
      become_user: "{{ ghost_user }}"

    #pm2
    - name: stop node apps
      command: pm2 delete all
      become: yes
      become_user: apps
      ignore_errors: yes
    - name: start node app
      command: pm2 start {{ item }} --name ghost
      become: yes
      become_user: apps
      with_items: pm2_apps
      environment:
        NODE_ENV: production
    - name: save pm2 processes
      command: pm2 save
      become: yes
      become_user: apps
    - name: installing startup script
      command: pm2 startup ubuntu -u apps
      environment:
        HOME: /var/apps
      notify:
        - start pm2

  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: restart nginx
      service: name=nginx state=restarted
    - name: start pm2
      service: name=pm2-init.sh state=started
