---
- hosts: all
  sudo: yes
  vars:

    nodejs_version: "0.10"
    nodejs_packages:
      - pm2

    ghost_version: "0.7.0"
    ghost_user: apps
    ghost_location: /var/apps/ghost-{{ ghost_version }}
    ghost_config: ./ghost/config.prod.js
    ghost_theme: https://github.com/mmarcon/ghost-jhere-beta/archive/master.zip

    github_url: https://github.com/mmarcon/jhere/branches/jsla3/dist/examples
    github_dest: /var/apps/jhere-examples
    github_files_owner: apps

    map_playground: https://github.com/thingsinjars/map-playground/archive/master.zip
    map_playground_config: ./map-playground/config.prod.json
    map_playground_processes: ./map-playground/processes.json

    # list of apps to be managed by pm2
    pm2_apps:
      - { path: "/var/apps/ghost-{{ ghost_version }}/index.js", name: "ghost" }
      - { path: "/var/apps/map-playground-master/processes.json", name: "map-playground" }

    nginx_sites:
      - default
      - bin

  vars_files:
    - vaults/mailgun.yml
    - vaults/github.yml

  roles:
    - nodejs
    - ghost
    - github

  pre_tasks:
    - name: create apps group
      group: name=apps state=present
    - name: create apps user
      user: name=apps comment="Apps User" group=apps home=/var/apps
    - name: create node apps directory
      file: path=/var/apps state=directory owner=apps group=apps mode=0775

  tasks:
    #nginx
    - name: install nginx
      apt: name=nginx state=present update_cache=yes
      notify:
        - start nginx
    - name: configure nginx
      copy: src={{ item }} dest=/etc/nginx/sites-available/
      with_fileglob:
        - ./nginx/*
      notify:
        - restart nginx
    - name: enable sites
      file: src=/etc/nginx/sites-available/{{item}} dest=/etc/nginx/sites-enabled/{{item}} state=link
      with_items: nginx_sites
      notify:
        - restart nginx

    #ghost theme
    - name: fetch theme
      get_url: url={{ghost_theme}} dest=/tmp/jhere-beta.zip
      become: yes
      become_user: "{{ ghost_user }}"
    - name: extract theme
      unarchive: src=/tmp/jhere-beta.zip dest={{ ghost_location }}/content/themes copy=no
      become: yes
      become_user: "{{ ghost_user }}"

    #playground
    - name: fetch playground
      get_url: url={{map_playground}} dest=/tmp/map-playground.zip
      become: yes
      become_user: "{{ ghost_user }}"
    - name: extract playground
      unarchive: src=/tmp/map-playground.zip dest=/var/apps copy=no
      become: yes
      become_user: "{{ ghost_user }}"
    - name: install playground dependencies
      command: npm install chdir=/var/apps/map-playground-master
      become: yes
      become_user: "{{ ghost_user }}"
    - name: configure playground
      copy: src={{ map_playground_config }} dest=/var/apps/map-playground-master/dist/config.json
      become: yes
      become_user: "{{ ghost_user }}"
    - name: copy pm2 setup
      copy: src={{ map_playground_processes }} dest=/var/apps/map-playground-master/processes.json
      become: yes
      become_user: "{{ ghost_user }}"
    - name: configure client id
      replace: dest=/var/apps/map-playground-master/dist/config.json regexp='GITHUB_CLIENT_ID' replace={{ github_client_id }}
      become: yes
      become_user: "{{ ghost_user }}"
      when: github_client_id is defined
    - name: configure client secret
      replace: dest=/var/apps/map-playground-master/dist/config.json regexp='GITHUB_CLIENT_SECRET' replace={{ github_client_secret }}
      become: yes
      become_user: "{{ ghost_user }}"
      when: github_client_secret is defined

    #pm2
    - name: stop node apps
      command: pm2 kill
      become: yes
      become_user: apps
      ignore_errors: yes
    - name: delete node apps
      command: pm2 delete all
      become: yes
      become_user: apps
      ignore_errors: yes
    - name: start node app
      command: pm2 start {{ item.path }} --name {{ item.name }}
      become: yes
      become_user: apps
      with_items: pm2_apps
      environment:
        NODE_ENV: production
    - name: save pm2 processes
      command: pm2 save
      become: yes
      become_user: apps
    - name: installing startup script
      command: pm2 startup ubuntu -u apps
      environment:
        HOME: /var/apps
      notify:
        - start pm2

  handlers:
    - name: start nginx
      service: name=nginx state=started
    - name: restart nginx
      service: name=nginx state=restarted
    - name: start pm2
      service: name=pm2-init.sh state=started
