---

- name: fetch files
  subversion: repo={{github_url}} dest={{github_dest}} export=yes force=yes
  become: yes
  become_user: "{{ github_files_owner }}"
  when: github_url is defined and github_dest is defined
